#!/bin/bash


fzwhere() {
    if [[ $1 == "-h" || $1 == "--help" ]]; then
        # Display a help message if the argument is "-h" or "--help"
        echo "Usage: fzwhere [OPTION]"
        echo "Search for anything using fzf and display its path."
        echo ""
        echo "Options:"
        echo "  no option   Search files within the current directory."
        echo "  root, r     Search files within the root directory (/)."
        echo "  home, h     Search files within the home directory (~/)."
        echo "  desktop, d  Search files within the desktop directory (~/Desktop/)."
        echo "  -h, --help  Display this help message and exit."
        return 1
    elif [[ $1 == "root" || $1 == "r" || $1 == "/" ]]; then
        # If the argument "root" is provided, search within the home directory
        fd --follow --hidden --exclude .git . / | fzf
    elif [[ $1 == "home" || $1 == "h" || $1 == "~" ]]; then
        # If the argument "home" is provided, search within the home directory
        fd --follow --hidden --exclude .git . ~/ | fzf
    elif [[ $1 == "desktop" || $1 == "d" ]]; then
        # If the argument "desktop" is provided, search within the desktop directory
        fd --follow --hidden --exclude .git . ~/Desktop | fzf
    else
        # Otherwise, search within the current directory
        fd --follow --hidden --exclude .git . | fzf
    fi
}


fzcd() {
    if [[ $1 == "-h" || $1 == "--help" ]]; then
        # Display a help message if the argument is "-h" or "--help"
        echo "Usage: fzcd [OPTION]"
        echo "Search for a directory using fzf and change to it."
        echo ""
        echo "Options:"
        echo "  no option   Search directories within the current directory."
        echo "  root, r     Search directories within the root directory (/)."
        echo "  home, h     Search directories within the home directory (~/)."
        echo "  desktop, d  Search directories within the desktop directory (~/Desktop/)."
        echo "  -h, --help  Display this help message and exit."
        return 1
    elif [[ $1 == "root" || $1 == "r" || $1 == "/" ]]; then
        # If the argument "root" is provided, search within the home directory
        cd "$(fd --type directory --follow --hidden --exclude .git . / | fzf --preview '')"
    elif [[ $1 == "home" || $1 == "h" || $1 == "~" ]]; then
        # If the argument "home" is provided, search within the home directory
        cd "$(fd --type directory --follow --hidden --exclude .git . ~/ | fzf --preview '')"
    
    elif [[ $1 == "desktop" || $1 == "d" ]]; then
        # If the argument "desktop" is provided, search within the desktop directory
        cd "$(fd --type directory --follow --hidden --exclude .git . ~/Desktop | fzf --preview '')"
    else
        # Otherwise, search within the current directory
        cd "$(fd --type directory --follow --hidden --exclude .git . | fzf --preview '')"
    fi
}


fzopen() {
    if [[ $1 == "-h" || $1 == "--help" ]]; then
        # Display a help message if the argument is "-h" or "--help"
        echo "Usage: fzopen [OPTION]"
        echo "Search for a file using fzf and open it."
        echo ""
        echo "Options:"
        echo "  no option   Search files within the current directory."
        echo "  root, r     Search files within the root directory (/)."
        echo "  home, h     Search files within the home directory (~/)."
        echo "  desktop, d  Search files within the desktop directory (~/Desktop/)."
        echo "  -h, --help  Display this help message and exit."
        return 1
    elif [[ $1 == "root" || $1 == "r" || $1 == "/" ]]; then
        # If the argument "root" is provided, search within the home directory
        TO_OPEN=$(fd --follow --hidden --exclude .git . / | fzf)
        # Only open the file if it exists
        [ -n "$TO_OPEN" ] && open $TO_OPEN
        if [ -e "$TO_OPEN" ]; then
            echo "Opening: $TO_OPEN"
        else
            return 1
        fi
    elif [[ $1 == "home" || $1 == "h" || $1 == "~" ]]; then
        # If the argument "home" is provided, search within the home directory
        TO_OPEN=$(fd --follow --hidden --exclude .git . ~/ | fzf)
        [ -n "$TO_OPEN" ] && open $TO_OPEN
        if [ -e "$TO_OPEN" ]; then
            echo "Opening: $TO_OPEN"
        else
            return 1
        fi
    elif [[ $1 == "desktop" || $1 == "d" ]]; then
        # If the argument "desktop" is provided, search within the desktop directory
        TO_OPEN=$(fd --follow --hidden --exclude .git . ~/Desktop | fzf)
        [ -n "$TO_OPEN" ] && open $TO_OPEN
        if [ -e "$TO_OPEN" ]; then
            echo "Opening: $TO_OPEN"
        else
            return 1
        fi
        
    else
        # Otherwise, search within the current directory
        TO_OPEN=$(fzf)
        [ -n "$TO_OPEN" ] && open $TO_OPEN
        if [ -e "$TO_OPEN" ]; then
            echo "Opening: $TO_OPEN"
        else
            return 1
        fi
    fi
}


fzcode() {
    if [[ $1 == "-h" || $1 == "--help" ]]; then
        # Display a help message if the argument is "-h" or "--help"
        echo "Usage: fzcode [OPTION]"
        echo "Search for a file using fzf and open it in Visual Studio Code."
        echo ""
        echo "Options:"
        echo "  no option   Search files within the current directory."
        echo "  root, r     Search files within the root directory (/)."
        echo "  home, h     Search files within the home directory (~/)."
        echo "  desktop, d  Search files within the desktop directory (~/Desktop/)."
        echo "  -h, --help  Display this help message and exit."
        return 1
    elif [[ $1 == "root" || $1 == "r" || $1 == "/" ]]; then
        # If the argument "root" is provided, search within the home directory
        TO_OPEN=$(fd --follow --hidden --exclude .git . / | fzf)
        [ -n "$TO_OPEN" ] && code $TO_OPEN
        #code $TO_OPEN
        #echo "Opening in VSCode: $TO_OPEN"
        if [ -e "$TO_OPEN" ]; then
            echo "Opening in VSCode: $TO_OPEN"
        else
            return 1
        fi
    elif [[ $1 == "home" || $1 == "h" || $1 == "~" ]]; then
        # If the argument "home" is provided, search within the home directory
        TO_OPEN=$(fd --follow --hidden --exclude .git . ~/ | fzf)
        [ -n "$TO_OPEN" ] && code $TO_OPEN
        #code $TO_OPEN
        #echo "Opening in VSCode: $TO_OPEN"
        if [ -e "$TO_OPEN" ]; then
            echo "Opening in VSCode: $TO_OPEN"
        else
            return 1
        fi
    elif [[ $1 == "desktop" || $1 == "d" ]]; then
        # If the argument "desktop" is provided, search within the desktop directory
        TO_OPEN=$(fd --follow --hidden --exclude .git . ~/Desktop | fzf)
        #code $TO_OPEN
        [ -n "$TO_OPEN" ] && code $TO_OPEN
        #echo "Opening in VSCode: $TO_OPEN"
        if [ -e "$TO_OPEN" ]; then
            echo "Opening in VSCode: $TO_OPEN"
        else
            return 1
        fi
    else
        # Otherwise, search within the current directory
        TO_OPEN=$(fzf)
        #code $TO_OPEN
        [ -n "$TO_OPEN" ] && code $TO_OPEN
        #echo "Opening in VSCode: $TO_OPEN"
        if [ -e "$TO_OPEN" ]; then
            echo "Opening in VSCode: $TO_OPEN"
        else
            return 1
        fi
    fi
}


fzmv() {}


fzcp() {}