#!/bin/bash

#rand=$(( $RANDOM % 2 ))

# If 0, run login_message_cow
#if [ $rand -eq 0 ]; then
    #login_message_cow
#else
    #login_message_pokemon
#fi

# ANSI color codes
# https://en.wikipedia.org/wiki/ANSI_escape_code#Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[0;37m'
NC='\033[0m' # No Color

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

# Underline
UBlack='\033[4;30m'       # Black
URed='\033[4;31m'         # Red
UGreen='\033[4;32m'       # Green
UYellow='\033[4;33m'      # Yellow
UBlue='\033[4;34m'        # Blue
UPurple='\033[4;35m'      # Purple
UCyan='\033[4;36m'        # Cyan
UWhite='\033[4;37m'       # White

# Background
On_Black='\033[40m'       # Black
On_Red='\033[41m'         # Red
On_Green='\033[42m'       # Green
On_Yellow='\033[43m'      # Yellow
On_Blue='\033[44m'        # Blue
On_Purple='\033[45m'      # Purple
On_Cyan='\033[46m'        # Cyan
On_White='\033[47m'       # White

B_U_RED='\033[1;4;31m' # Bold, Underline, Red
B_U_YELLOW='\033[1;4;33m' # Bold, Underline, Yellow
B_U_GREEN='\033[1;4;32m' # Bold, Underline, Green


# Welcome message
echo -e "${B_U_YELLOW}Welcome to the terminal $USER ⊂(◉‿◉)つ${NC}"
echo -e "${BGreen}$(date +"%a %m/%d/%Y %r %Z")${NC}"
echo -e "${BCyan}$(uname -n -o -p)${NC}"
#echo -e "${BRed}Press Ctrl+C to stop the update checking\n& welcome message, and get to work!${NC}\n"
echo -e "${BRed}Would you like to check for updates (Y/N)${NC}"
read -n 1 -r ANSWER
#echo -e "${BWhite}$(uptime)${NC}"

if [[ $ANSWER =~ ^[Yy]$ ]]; then
    echo -e "\n\n${B_U_GREEN}Checking for updates...${NC}"
    # Check for updates
    echo -e "${MAGENTA}Updating Homebrew & Homebrew Packages 🍺${NC}"
    brew update
    brew upgrade
    brew cleanup

    echo -e "${MAGENTA}Updating Pip Packages 🐍${NC}"
    pip list --outdated | awk 'NR>1 {print $1}' | xargs -n1 pip install -U
    pip install -U pip

    #echo -e "${MAGENTA}Updating NodeJS ${NC}"
    #nvm install node --reinstall-packages-from=node

    echo -e "${MAGENTA}Updating Global NPM Packages 📦${NC}"
    npm update -g

    echo -e "${MAGENTA}Updating Mojo 🔥${NC}"
    modular update mojo

    # Actual message
    echo -e "\n"
    login_message_pokemon
else
    #echo -e "\n\n${BRed}Skipping updates...${NC}\n"
    echo -e "\n"
    login_message_pokemon
    exit 0
fi