#!/bin/bash

file_name=$1
to_dir=$2
from_dir=$(pwd)

if test "$#" -eq 0  || test "$#" -gt 3; then
    echo "Moves a file to a new directory and creates a link back to the original location (by default)."
    echo "Usage: mk_and_link file_name to_dir [from_dir]"
    echo "Parameters:"
    echo "  file_name: name of file to move"
    echo "  to_dir: directory to move file to"
    echo "  [from_dir: directory to move file from]"
    echo "    default: current directory"
    exit 1
fi

# Set from_dir if third argument is given
if test "$#" -eq 3; then
    from_dir=$3
fi

echo "Moving File:"
echo "$from_dir/$file_name --> $to_dir/"

# Move file
mv $from_dir/$file_name $to_dir/

# Create link back to original location
mk_link $file_name $to_dir $from_dir